import image from "../../assets/Images/blog.png";
import Prince from "../../assets/Images/Prince.png";

export const Blogdata = [
  {
    id: 1,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 2,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    image2: "",
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 3,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 4,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 5,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 6,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 7,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 8,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 9,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 10,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 11,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 12,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 13,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 14,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
  {
    id: 15,
    title: "Desire Residence",
    location: "Andheri East,Mumbai",
    image: image,
    designed: "Gautam Singh",
    customer: Prince,
  },
];
